/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Reportes;
import ConexionLogin.Conexion;
import ConexionLogin.SesionUsuario;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Paper;
import java.awt.print.Printable;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.Timer;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rafael
 */
public class ImprimirReportesMantenimiento extends javax.swing.JFrame implements Printable {

    /**
     * Creates new form ImprimirReportesMantenimiento
     */
    public ImprimirReportesMantenimiento(String ru, String estado, Date fechaDesde, Date fechaHasta) {
        initComponents();
        Nombretxt.setText(SesionUsuario.nombre + " " + SesionUsuario.apellido);
        RUtxt.setText(SesionUsuario.username);
        CItxt.setText(String.valueOf(SesionUsuario.ci));
        telefonotxt.setText(SesionUsuario.telefono);
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        String fechaDesdeStr = (fechaDesde != null) ? dateFormat.format(fechaDesde) : "Todos";
        String fechaHastaStr = (fechaHasta != null) ? dateFormat.format(fechaHasta) : "Todos";
        

        
        cargarTablaFiltrada(ru, estado, fechaDesde, fechaHasta);

        
        this.setLocationRelativeTo(null);

        
        Usuariotxt.setText(ru);
        Estadotxt.setText(estado);
        Desdetxt.setText(fechaDesdeStr);
        Hastatxt.setText(fechaHastaStr);
    }

    private ImprimirReportesMantenimiento() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Imprimir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReportes = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Fechatxt = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        ReportesPrestamos = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        Nombretxt = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        CIlbl = new javax.swing.JLabel();
        CItxt = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        RUtxt = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        telefonolbl = new javax.swing.JLabel();
        telefonotxt = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        Hastatxt = new javax.swing.JLabel();
        Desdetxt = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Usuariotxt = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        Estadotxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Imprimir.setText("Imprimir");
        Imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImprimirActionPerformed(evt);
            }
        });
        jPanel1.add(Imprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 690, -1, -1));

        tblReportes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Codigo", "Laboratorio", "Estado", "Fecha", "Descripcion", "Realizado Por"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        // Definir los anchos de las columnas
        int[] anchos = {44, 125, 107, 95, 84, 373, 100};
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();

        // Iterar sobre las columnas y ajustar su tamaño
        for (int i = 0; i < anchos.length; i++) {
            tblReportes.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
            tblReportes.getColumnModel().getColumn(i).setCellRenderer(centerRenderer); // Alineación centrada
        }
        jScrollPane1.setViewportView(tblReportes);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 930, 400));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Sistema de Control y Prestamos de Laboratorios de Hardware, Electronica, Redes y Telecomunicaciones");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 7, -1, -1));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoUSB.png"))); // NOI18N
        jPanel8.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 60));

        jPanel3.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 0, 180, 60));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Fecha:");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 35, 40, 20));

        Date fechaActual = new Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        String fechaFormateada = dateFormat.format(fechaActual);
        Fechatxt.setText(fechaFormateada);
        Fechatxt.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.add(Fechatxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 35, 180, 20));

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 930, 60));

        ReportesPrestamos.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        ReportesPrestamos.setText("Reporte de Mantenimiento");
        jPanel1.add(ReportesPrestamos, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 73, -1, -1));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("DATOS DEL TRABAJADOR QUE PRESENTO EL REPORTE");
        jPanel9.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 2, -1, -1));

        jPanel7.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 20));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Nombretxt.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.add(Nombretxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 25, 370, 20));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Nombre:");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 25, -1, 20));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CIlbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CIlbl.setText("Carnet de Identidad:");
        jPanel11.add(CIlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 37, -1, -1));
        jPanel11.add(CItxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 35, 320, 20));

        jPanel5.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, -10, 480, 60));

        jPanel7.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 50));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("RU:");
        jPanel10.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 47, -1, -1));
        jPanel10.add(RUtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 45, 380, 20));

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        telefonolbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        telefonolbl.setText("Numero de Telefono:");
        jPanel12.add(telefonolbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 37, -1, -1));
        jPanel12.add(telefonotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 35, 320, 20));

        jPanel10.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 480, 60));

        jPanel7.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 930, 70));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 930, 80));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("DETALLES");
        jPanel14.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 2, -1, -1));

        jPanel6.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 20));

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Hasta:");
        jPanel16.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 20));
        jPanel16.add(Hastatxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 240, 20));

        jPanel15.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 480, 40));
        jPanel15.add(Desdetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 240, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Desde:");
        jPanel15.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 20));

        jPanel6.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 50));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText("Usuario:");
        jPanel6.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 50, 20));
        jPanel6.add(Usuariotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 240, 20));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText("Estado:");
        jPanel6.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, -1, 20));
        jPanel6.add(Estadotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, 240, 20));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 930, 80));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents
        private void cargarTablaFiltrada(String ru, String estado, Date fechaDesde, Date fechaHasta) {
        try {
            Connection con = Conexion.obtenerConexion();

            String query = "SELECT m.id_mantenimiento, mh.nombre AS material_nombre, l.Codigo_lab, "
                    + "mh.estado, m.fecha, m.descripcion, CONCAT(te.nombre, ' ', te.apellido) AS tecnico_nombre "
                    + "FROM mantenimiento m "
                    + "INNER JOIN materiales_hardware mh ON m.id_material_hardware = mh.id_material_hardware "
                    + "INNER JOIN laboratorios l ON mh.ID_lab = l.ID_lab "
                    + "INNER JOIN tecnico_equipos te ON m.id_tecnico_equipos = te.id_tecnico_equipos "
                    + "WHERE 1=1 ";

            List<Object> parametros = new ArrayList<>();

            if (ru != null && !ru.isEmpty()) {
                query += " AND te.RU = ?";
                parametros.add(ru);
            }

            if (estado != null && !"Todos".equals(estado)) {
                query += " AND mh.estado = ?";
                parametros.add(estado);
            }

            if (fechaDesde != null && fechaHasta != null) {
                query += " AND m.fecha BETWEEN ? AND ?";
                parametros.add(new java.sql.Date(fechaDesde.getTime()));
                parametros.add(new java.sql.Date(fechaHasta.getTime()));
            }

            PreparedStatement ps = con.prepareStatement(query);

            for (int i = 0; i < parametros.size(); i++) {
                ps.setObject(i + 1, parametros.get(i));
            }

            ResultSet rs = ps.executeQuery();
            DefaultTableModel model = (DefaultTableModel) tblReportes.getModel();
            model.setRowCount(0);

            while (rs.next()) {
                model.addRow(new Object[]{
                        rs.getInt("id_mantenimiento"),
                        rs.getString("material_nombre"),
                        rs.getString("Codigo_lab"),
                        rs.getString("estado"),
                        rs.getDate("fecha"),
                        rs.getString("descripcion"),
                        rs.getString("tecnico_nombre")
                });
            }

        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al cargar datos filtrados.");
        }
    }
    @Override
    public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
        if (pageIndex > 0) {
            return NO_SUCH_PAGE;
        }

        // Usamos márgenes estrechos: ya definidos en setPrintable()
        Graphics2D g2d = (Graphics2D) graphics;
        g2d.translate(pageFormat.getImageableX(), pageFormat.getImageableY());

        // Escalar si el contenido es muy grande
        g2d.scale(0.8, 0.8);

        // Fondo blanco (opcional si ya es blanco)
        g2d.setColor(Color.WHITE);
        g2d.fillRect(0, 0, jPanel1.getWidth(), jPanel1.getHeight());

        // Pintar solo contenido sin estilos adicionales
        jPanel1.printAll(g2d);

        return PAGE_EXISTS;
    }
    private void ImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImprimirActionPerformed
        Imprimir.setVisible(false);

        PrinterJob printerJob = PrinterJob.getPrinterJob();

        // Configuración de página con márgenes estrechos y horizontal
        PageFormat format = printerJob.defaultPage();
        format.setOrientation(PageFormat.LANDSCAPE);

        Paper paper = format.getPaper();
        double margin = 20; // 20 puntos ≈ 0.7 cm

        double width = paper.getWidth();
        double height = paper.getHeight();
        paper.setImageableArea(margin, margin, width - 2 * margin, height - 2 * margin);
        format.setPaper(paper);

        printerJob.setPrintable(this, format);

        if (printerJob.printDialog()) {
            try {
                printerJob.print();
            } catch (PrinterException ex) {
                ex.printStackTrace();
            }
        }

        Imprimir.setVisible(true);
        dispose();
    }//GEN-LAST:event_ImprimirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImprimirReportesMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImprimirReportesMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImprimirReportesMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImprimirReportesMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception e){
            e.printStackTrace();
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ImprimirReportesMantenimiento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CIlbl;
    private javax.swing.JLabel CItxt;
    private javax.swing.JLabel Desdetxt;
    private javax.swing.JLabel Estadotxt;
    private javax.swing.JLabel Fechatxt;
    private javax.swing.JLabel Hastatxt;
    private javax.swing.JButton Imprimir;
    private javax.swing.JLabel Nombretxt;
    private javax.swing.JLabel RUtxt;
    private javax.swing.JLabel ReportesPrestamos;
    private javax.swing.JLabel Usuariotxt;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblReportes;
    private javax.swing.JLabel telefonolbl;
    private javax.swing.JLabel telefonotxt;
    // End of variables declaration//GEN-END:variables
}
