/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Reportes;

import ConexionLogin.Conexion;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Paper;
import java.awt.print.Printable;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.Timer;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rafael
 */
public class ImprimirReportesPrestamos extends javax.swing.JFrame implements Printable {

    /**
     * Creates new form ImprimirReportesPrestamos
     */
    public ImprimirReportesPrestamos(String ru, String seccion, String estado, Date fechaDesde, Date fechaHasta) {
        initComponents();
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        String fechaDesdeStr = (fechaDesde != null) ? dateFormat.format(fechaDesde) : "Todos";
        String fechaHastaStr = (fechaHasta != null) ? dateFormat.format(fechaHasta) : "Todos";

        cargarTablaFiltrada(ru, seccion, estado, fechaDesde, fechaHasta);

        this.setLocationRelativeTo(null);

        Usuariotxt.setText(ru);
        Secciontxt.setText(seccion);
        Estadotxt.setText(estado);
        Desdetxt.setText(fechaDesdeStr);
        Hastatxt.setText(fechaHastaStr);

    }

    private ImprimirReportesPrestamos() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReportes = new javax.swing.JTable();
        ReportesPrestamos = new javax.swing.JLabel();
        Imprimir = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Secciontxt = new javax.swing.JLabel();
        Usuariotxt = new javax.swing.JLabel();
        Estadotxt = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Desdetxt = new javax.swing.JLabel();
        Hastatxt = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Nombretxt = new javax.swing.JLabel();
        Fechatxt = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblReportes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Docente", "Seccion", "Laboratorio", "Fecha", "Horario Inicio", "Horario Fin", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblReportes);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 930, 460));

        ReportesPrestamos.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        ReportesPrestamos.setText("Reportes de Prestamos");
        jPanel1.add(ReportesPrestamos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 250, -1));

        Imprimir.setText("Imprimir");
        Imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImprimirActionPerformed(evt);
            }
        });
        jPanel1.add(Imprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("Usuario:");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));

        jLabel4.setText("Estado:");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, -1, 20));

        jLabel3.setText("Sección:");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 50, 20));
        jPanel4.add(Secciontxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 180, 20));
        jPanel4.add(Usuariotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 180, 20));
        jPanel4.add(Estadotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 220, 20));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 930, 50));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Desde:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));

        jLabel6.setText("Hasta:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 40, 20));
        jPanel2.add(Desdetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 240, 20));
        jPanel2.add(Hastatxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 240, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 920, 50));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setText("Nombre:");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));

        jLabel10.setText("Fecha:");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 40, 20));
        jPanel5.add(Nombretxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 240, 20));

        Date fechaActual = new Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        String fechaFormateada = dateFormat.format(fechaActual);
        Fechatxt.setText(fechaFormateada);
        jPanel5.add(Fechatxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 240, 20));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 920, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void cargarTablaFiltrada(String ru, String seccion, String estado, Date fechaDesde, Date fechaHasta) {
        try {
            Connection con = Conexion.obtenerConexion();

            String query = "SELECT p.id_prestamo, l.Nombre_lab, CONCAT(pa.nombre, ' ', pa.apellido) AS docente, "
                    + "l.Seccion, p.fecha, p.horario_inicio, p.horario_fin, p.estado "
                    + "FROM prestamos p "
                    + "INNER JOIN laboratorios l ON p.ID_lab = l.ID_lab "
                    + "INNER JOIN personal_academico pa ON p.id_personal_academico = pa.id_personal_academico "
                    + "WHERE 1=1";

            List<Object> parametros = new ArrayList<>();

            if (ru != null && !ru.isEmpty()) {
                query += " AND pa.RU = ?";
                parametros.add(ru);
            }
            if (seccion != null && !"Todos".equals(seccion)) {
                query += " AND l.Seccion = ?";
                parametros.add(seccion);
            }
            if (estado != null && !"Todos".equals(estado)) {
                query += " AND p.estado = ?";
                parametros.add(estado);
            }

            if (fechaDesde != null && fechaHasta != null) {
                query += " AND p.fecha BETWEEN ? AND ?";
                parametros.add(new java.sql.Date(fechaDesde.getTime()));
                parametros.add(new java.sql.Date(fechaHasta.getTime()));
            }

            PreparedStatement ps = con.prepareStatement(query);

            for (int i = 0; i < parametros.size(); i++) {
                ps.setObject(i + 1, parametros.get(i));
            }

            ResultSet rs = ps.executeQuery();
            DefaultTableModel model = (DefaultTableModel) tblReportes.getModel();
            model.setRowCount(0);

            while (rs.next()) {
                model.addRow(new Object[]{
                        rs.getInt("id_prestamo"),
                        rs.getString("docente"),
                        rs.getString("Seccion"),
                        rs.getString("Nombre_Lab"),
                        rs.getDate("fecha"),
                        rs.getString("horario_inicio"),
                        rs.getString("horario_fin"),
                        rs.getString("estado"),
                });
            }

        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al cargar datos filtrados.");
        }
    }
    @Override
    public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
        if (pageIndex > 0) {
            return NO_SUCH_PAGE;
        }

        // Usamos márgenes estrechos: ya definidos en setPrintable()
        Graphics2D g2d = (Graphics2D) graphics;
        g2d.translate(pageFormat.getImageableX(), pageFormat.getImageableY());

        // Escalar si el contenido es muy grande
        g2d.scale(0.8, 0.8);

        // Fondo blanco (opcional si ya es blanco)
        g2d.setColor(Color.WHITE);
        g2d.fillRect(0, 0, jPanel1.getWidth(), jPanel1.getHeight());

        // Pintar solo contenido sin estilos adicionales
        jPanel1.printAll(g2d);

        return PAGE_EXISTS;
    }
    private void ImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImprimirActionPerformed
        Imprimir.setVisible(false);

        PrinterJob printerJob = PrinterJob.getPrinterJob();

        // Configuración de página con márgenes estrechos y horizontal
        PageFormat format = printerJob.defaultPage();
        format.setOrientation(PageFormat.LANDSCAPE);

        Paper paper = format.getPaper();
        double margin = 20; // 20 puntos ≈ 0.7 cm

        double width = paper.getWidth();
        double height = paper.getHeight();
        paper.setImageableArea(margin, margin, width - 2 * margin, height - 2 * margin);
        format.setPaper(paper);

        printerJob.setPrintable(this, format);

        if (printerJob.printDialog()) {
            try {
                printerJob.print();
            } catch (PrinterException ex) {
                ex.printStackTrace();
            }
        }

        Imprimir.setVisible(true);
        dispose();
    }//GEN-LAST:event_ImprimirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImprimirReportesPrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImprimirReportesPrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImprimirReportesPrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImprimirReportesPrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ImprimirReportesPrestamos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Desdetxt;
    private javax.swing.JLabel Estadotxt;
    private javax.swing.JLabel Fechatxt;
    private javax.swing.JLabel Hastatxt;
    private javax.swing.JButton Imprimir;
    private javax.swing.JLabel Nombretxt;
    private javax.swing.JLabel ReportesPrestamos;
    private javax.swing.JLabel Secciontxt;
    private javax.swing.JLabel Usuariotxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblReportes;
    // End of variables declaration//GEN-END:variables
}
