/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Reportes;

import ConexionLogin.Conexion;
import java.util.List;
import java.util.ArrayList;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;

import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rafael
 */
public class ReportesPrestamos extends javax.swing.JFrame {

    /**
     * Creates new form ReportesPrestamos
     */
    public ReportesPrestamos() {
        initComponents();
        cargarTablaTodo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Superior = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReportes = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        SeccionBox = new javax.swing.JComboBox<>();
        EstadoPrestamo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        RUtxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Buscar = new javax.swing.JButton();
        Limpiar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        FechaDesde = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        FechaHasta = new com.toedter.calendar.JDateChooser();
        AsignacionSancion = new javax.swing.JLabel();
        AsignacionSancion1 = new javax.swing.JLabel();
        FondoGris = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Superior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/SuperiorInterfaz.png"))); // NOI18N
        getContentPane().add(Superior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1540, 60));

        tblReportes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Prestamo", "Docente", "Seccion", "Laboratorio", "Fecha", "Horario Inicio", "Horario Fin", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblReportes);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 1480, 490));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Solicitudes en Seccion de:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 150, 20));

        SeccionBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sin Seleccionar", "Hardware", "Redes", "Telecomunicaciones", "Electronica"}));
        jPanel1.add(SeccionBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 220, -1));

        EstadoPrestamo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sin Seleccionar", "Aprobado", "Rechazado", "Pendiente"}));
        jPanel1.add(EstadoPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 220, -1));

        jLabel4.setText("Estado del Prestamo:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 20));

        RUtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RUtxtActionPerformed(evt);
            }
        });
        jPanel1.add(RUtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 220, -1));

        jLabel5.setText("RU del Solicitante");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, 20));

        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });
        jPanel1.add(Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        Limpiar.setText("Limpiar");
        Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(Limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, -1));

        jLabel2.setText("Apertura desde:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, -1, 20));
        jPanel1.add(FechaDesde, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 40, 220, -1));

        jLabel1.setText("Apertura hasta:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, -1, 20));
        jPanel1.add(FechaHasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, 220, -1));

        AsignacionSancion.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        AsignacionSancion.setText("Fecha de Prestamo");
        jPanel1.add(AsignacionSancion, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 200, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 790, 190));

        AsignacionSancion1.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        AsignacionSancion1.setText("Reportes de Prestamos");
        getContentPane().add(AsignacionSancion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 250, -1));

        FondoGris.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo_3.png"))); // NOI18N
        getContentPane().add(FondoGris, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1540, 870));

        pack();
    }// </editor-fold>//GEN-END:initComponents
        public void cargarTablaTodo() {
        try {
            Connection con = Conexion.obtenerConexion();

            String query = "SELECT p.id_prestamo, l.Nombre_lab, CONCAT(pa.nombre, ' ', pa.apellido) AS docente, "
                    + "l.Seccion, p.fecha, p.horario_inicio, p.horario_fin, p.estado "
                    + "FROM prestamos p "
                    + "INNER JOIN laboratorios l ON p.ID_lab = l.ID_lab "
                    + "INNER JOIN personal_academico pa ON p.id_personal_academico = pa.id_personal_academico";

            PreparedStatement ps = con.prepareStatement(query);
            ResultSet rs = ps.executeQuery();
            DefaultTableModel model = (DefaultTableModel) tblReportes.getModel();
            model.setRowCount(0);

            while (rs.next()) {
                int idPrestamo = rs.getInt("id_prestamo");
                String docente = rs.getString("docente");
                String seccion = rs.getString("Seccion");
                String nombreLab = rs.getString("Nombre_lab");
                Date fecha = rs.getDate("fecha");
                Time horaInicio = rs.getTime("horario_inicio");
                Time horaFin = rs.getTime("horario_fin");
                String estado = rs.getString("estado");
                

                model.addRow(new Object[]{
                    idPrestamo, docente, seccion, nombreLab, fecha, horaInicio, horaFin, estado
                });
            }

        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }
    }
    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
    String seccion = SeccionBox.getSelectedItem().toString();
    String estado = EstadoPrestamo.getSelectedItem().toString();
    String ru = RUtxt.getText().trim();

    Date fechaInicio = FechaDesde.getDate();
    Date fechaFin = FechaHasta.getDate();

    String query = "SELECT p.id_prestamo, l.Nombre_lab, CONCAT(pa.nombre, ' ', pa.apellido) AS docente, "
            + "l.Seccion, p.fecha, p.horario_inicio, p.horario_fin, p.estado "
            + "FROM prestamos p "
            + "INNER JOIN laboratorios l ON p.ID_lab = l.ID_lab "
            + "INNER JOIN personal_academico pa ON p.id_personal_academico = pa.id_personal_academico "
            + "WHERE 1=1";

    List<Object> parametros = new ArrayList<>();

    // Filtrar por sección si se ha seleccionado una opción válida
    if (!"Sin Seleccionar".equals(seccion)) {
        query += " AND l.Seccion = ?";
        parametros.add(seccion);
    }

    // Filtrar por estado si se ha seleccionado una opción válida
    if (!"Sin Seleccionar".equals(estado)) {
        query += " AND p.estado = ?";
        parametros.add(estado);
    }

    // Filtrar por RU si no está vacío
    if (!ru.isEmpty()) {
        query += " AND pa.RU = ?";
        parametros.add(ru);
    }

    // Filtrar por fechas solo si ambas fechas están seleccionadas
    if (fechaInicio != null && fechaFin != null) {
        query += " AND p.fecha BETWEEN ? AND ?";
        parametros.add(new java.sql.Date(fechaInicio.getTime()));
        parametros.add(new java.sql.Date(fechaFin.getTime()));
    }

    try {
        Connection con = Conexion.obtenerConexion();
        PreparedStatement ps = con.prepareStatement(query);

        // Setear los parámetros en la consulta
        for (int i = 0; i < parametros.size(); i++) {
            ps.setObject(i + 1, parametros.get(i));
        }

        ResultSet rs = ps.executeQuery();
        DefaultTableModel model = (DefaultTableModel) tblReportes.getModel();
        model.setRowCount(0);  // Limpiar la tabla antes de agregar los nuevos resultados

        // Recorrer los resultados y agregarlos a la tabla
        while (rs.next()) {
            int idPrestamo = rs.getInt("id_prestamo");
            String docente = rs.getString("docente");
            String secc = rs.getString("Seccion");
            String nombreLab = rs.getString("Nombre_lab");
            Date fecha = rs.getDate("fecha");
            Time horaInicio = rs.getTime("horario_inicio");
            Time horaFin = rs.getTime("horario_fin");
            String est = rs.getString("estado");

            model.addRow(new Object[]{
                idPrestamo, docente, secc, nombreLab, fecha, horaInicio, horaFin, est
            });
        }

    } catch (SQLException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error al buscar los préstamos.");
    }
    }//GEN-LAST:event_BuscarActionPerformed

    private void RUtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RUtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RUtxtActionPerformed

    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed
        SeccionBox.setSelectedIndex(0);
        EstadoPrestamo.setSelectedIndex(0);
        RUtxt.setText("");
        FechaDesde.setDate(null);
        FechaHasta.setDate(null);
        cargarTablaTodo();
    }//GEN-LAST:event_LimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportesPrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportesPrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportesPrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportesPrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportesPrestamos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AsignacionSancion;
    private javax.swing.JLabel AsignacionSancion1;
    private javax.swing.JButton Buscar;
    private javax.swing.JComboBox<String> EstadoPrestamo;
    private com.toedter.calendar.JDateChooser FechaDesde;
    private com.toedter.calendar.JDateChooser FechaHasta;
    private javax.swing.JLabel FondoGris;
    private javax.swing.JButton Limpiar;
    private javax.swing.JTextField RUtxt;
    private javax.swing.JComboBox<String> SeccionBox;
    private javax.swing.JLabel Superior;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblReportes;
    // End of variables declaration//GEN-END:variables
}
