/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Reportes;

import ConexionLogin.Conexion;
import java.util.List;
import java.util.ArrayList;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;

import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rafael
 */
public class ReportesPrestamos extends javax.swing.JFrame {

    /**
     * Creates new form ReportesPrestamos
     */
    public ReportesPrestamos() {
        initComponents();
        cargarTablaTodo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Superior = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        FechaDesde = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        FechaHasta = new com.toedter.calendar.JDateChooser();
        AsignacionSancion = new javax.swing.JLabel();
        BuscarFechas = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReportes = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        SeccionBox = new javax.swing.JComboBox<>();
        EstadoPrestamo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        RUtxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Buscar = new javax.swing.JButton();
        BuscarSeccion = new javax.swing.JButton();
        BuscarEstado = new javax.swing.JButton();
        BuscarRU = new javax.swing.JButton();
        AsignacionSancion1 = new javax.swing.JLabel();
        FondoGris = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Superior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/SuperiorInterfaz.png"))); // NOI18N
        getContentPane().add(Superior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1540, 60));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Apertura desde:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 20));
        jPanel2.add(FechaDesde, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 220, -1));

        jLabel1.setText("Apertura hasta:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, 20));
        jPanel2.add(FechaHasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 220, -1));

        AsignacionSancion.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        AsignacionSancion.setText("Fecha de Prestamo");
        jPanel2.add(AsignacionSancion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, -1));

        BuscarFechas.setText("Buscar");
        BuscarFechas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarFechasActionPerformed(evt);
            }
        });
        jPanel2.add(BuscarFechas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, 470, 190));

        tblReportes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Prestamo", "Docente", "Seccion", "Laboratorio", "Fecha", "Horario Inicio", "Horario Fin", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblReportes);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 1480, 450));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Solicitudes en Seccion de:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 150, 20));

        SeccionBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hardware", "Redes", "Telecomunicaciones", "Electronica", "Todo"}));
        jPanel1.add(SeccionBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 220, -1));

        EstadoPrestamo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aprobado", "Rechazado", "Pendiente"}));
        jPanel1.add(EstadoPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 220, -1));

        jLabel4.setText("Estado del Prestamo:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 20));
        jPanel1.add(RUtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 220, -1));

        jLabel5.setText("RU del Solicitante");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, 20));

        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });
        jPanel1.add(Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        BuscarSeccion.setText("Buscar");
        BuscarSeccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarSeccionActionPerformed(evt);
            }
        });
        jPanel1.add(BuscarSeccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, 20, -1));

        BuscarEstado.setText("Buscar");
        BuscarEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarEstadoActionPerformed(evt);
            }
        });
        jPanel1.add(BuscarEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 20, -1));

        BuscarRU.setText("Buscar");
        BuscarRU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarRUActionPerformed(evt);
            }
        });
        jPanel1.add(BuscarRU, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 20, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 470, 190));

        AsignacionSancion1.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        AsignacionSancion1.setText("Reportes de Prestamos");
        getContentPane().add(AsignacionSancion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 250, -1));

        FondoGris.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo_3.png"))); // NOI18N
        getContentPane().add(FondoGris, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1540, 870));

        pack();
    }// </editor-fold>//GEN-END:initComponents
        public void cargarTablaTodo() {
        try {
            Connection con = Conexion.obtenerConexion();

            String query = "SELECT p.id_prestamo, l.Nombre_lab, CONCAT(pa.nombre, ' ', pa.apellido) AS docente, "
                    + "l.Seccion, p.fecha, p.horario_inicio, p.horario_fin, p.estado "
                    + "FROM prestamos p "
                    + "INNER JOIN laboratorios l ON p.ID_lab = l.ID_lab "
                    + "INNER JOIN personal_academico pa ON p.id_personal_academico = pa.id_personal_academico";

            PreparedStatement ps = con.prepareStatement(query);
            ResultSet rs = ps.executeQuery();
            DefaultTableModel model = (DefaultTableModel) tblReportes.getModel();
            model.setRowCount(0);

            while (rs.next()) {
                int idPrestamo = rs.getInt("id_prestamo");
                String docente = rs.getString("docente");
                String seccion = rs.getString("Seccion");
                String nombreLab = rs.getString("Nombre_lab");
                Date fecha = rs.getDate("fecha");
                Time horaInicio = rs.getTime("horario_inicio");
                Time horaFin = rs.getTime("horario_fin");
                String estado = rs.getString("estado");
                

                model.addRow(new Object[]{
                    idPrestamo, docente, seccion, nombreLab, fecha, horaInicio, horaFin, estado
                });
            }

        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }
    }
    private void BuscarFechasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarFechasActionPerformed
        java.util.Date fechainicial = FechaDesde.getDate();
        java.util.Date fechafinal = FechaHasta.getDate();

        if (fechainicial == null || fechafinal == null) {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione ambas fechas.");
            return;
        }

        java.sql.Date fechaInicioSQL = new java.sql.Date(fechainicial.getTime());
        java.sql.Date fechaFinSQL = new java.sql.Date(fechafinal.getTime());

        try {
            Connection con = Conexion.obtenerConexion();

            String query = "SELECT p.id_prestamo, l.Nombre_lab, CONCAT(pa.nombre, ' ', pa.apellido) AS docente, "
                    + "l.Seccion, p.fecha, p.horario_inicio, p.horario_fin, p.estado "
                    + "FROM prestamos p "
                    + "INNER JOIN laboratorios l ON p.ID_lab = l.ID_lab "
                    + "INNER JOIN personal_academico pa ON p.id_personal_academico = pa.id_personal_academico "
                    + "WHERE p.fecha BETWEEN ? AND ?";

            PreparedStatement ps = con.prepareStatement(query);
            ps.setDate(1, fechaInicioSQL);
            ps.setDate(2, fechaFinSQL);

            ResultSet rs = ps.executeQuery();

            DefaultTableModel model = (DefaultTableModel) tblReportes.getModel();
            model.setRowCount(0);

            boolean found = false;
            while (rs.next()) {
                found = true;
                int idPrestamo = rs.getInt("id_prestamo");
                String docente = rs.getString("docente");
                String seccion = rs.getString("Seccion");
                String nombreLab = rs.getString("Nombre_lab");
                Date fecha = rs.getDate("fecha");
                Time horaInicio = rs.getTime("horario_inicio");
                Time horaFin = rs.getTime("horario_fin");
                String estado = rs.getString("estado");

                model.addRow(new Object[]{
                    idPrestamo, docente, seccion, nombreLab, fecha, horaInicio, horaFin, estado
                });
            }

            if (!found) {
                JOptionPane.showMessageDialog(this, "No se encontraron registros en el rango de fechas seleccionado.");
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al acceder a la base de datos: " + ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_BuscarFechasActionPerformed

    private void BuscarSeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarSeccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarSeccionActionPerformed

    private void BuscarEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarEstadoActionPerformed

    private void BuscarRUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarRUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarRUActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportesPrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportesPrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportesPrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportesPrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportesPrestamos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AsignacionSancion;
    private javax.swing.JLabel AsignacionSancion1;
    private javax.swing.JButton Buscar;
    private javax.swing.JButton BuscarEstado;
    private javax.swing.JButton BuscarFechas;
    private javax.swing.JButton BuscarRU;
    private javax.swing.JButton BuscarSeccion;
    private javax.swing.JComboBox<String> EstadoPrestamo;
    private com.toedter.calendar.JDateChooser FechaDesde;
    private com.toedter.calendar.JDateChooser FechaHasta;
    private javax.swing.JLabel FondoGris;
    private javax.swing.JTextField RUtxt;
    private javax.swing.JComboBox<String> SeccionBox;
    private javax.swing.JLabel Superior;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblReportes;
    // End of variables declaration//GEN-END:variables
}
