import com.formdev.flatlaf.FlatLightLaf;
import java.sql.Connection;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.*;
import java.util.Date;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Rafael
 */
public class FormularioPrestamo extends javax.swing.JFrame {

    /**
     * Creates new form FormularioPrestamo
     */
    public FormularioPrestamo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LogoSale = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Nombre = new javax.swing.JTextField();
        Motivo = new javax.swing.JTextField();
        fecha = new com.toedter.calendar.JDateChooser();
        BloqueComboBox = new javax.swing.JComboBox<>();
        LaboratorioComboBox = new javax.swing.JComboBox<>();
        HorarioSpinner = new javax.swing.JSpinner();
        guardar = new javax.swing.JButton();
        Limpiar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Superior = new javax.swing.JLabel();
        Izquierda = new javax.swing.JLabel();
        ListaPersonal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaPrestamos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LogoSale.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logosaleint.png"))); // NOI18N
        getContentPane().add(LogoSale, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 170, 60));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(194, 194, 194)));
        jPanel1.setToolTipText("");
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Motivo del Prestamo");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 20));

        jLabel5.setText("Fecha:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, 20));

        jLabel6.setText("Bloque:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, 20));

        jLabel7.setText("Nombre del Solicitante:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 20));

        jLabel8.setText("Laboratorio:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, 20));

        jLabel1.setText("Horario:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel2.setText("Disponibilidad");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));
        jPanel1.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 350, -1));
        jPanel1.add(Motivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 350, -1));
        jPanel1.add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 350, -1));

        BloqueComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        BloqueComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BloqueComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(BloqueComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 350, -1));

        LaboratorioComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(LaboratorioComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 350, -1));
        jPanel1.add(HorarioSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 350, -1));

        guardar.setBackground(new java.awt.Color(29, 41, 57));
        guardar.setForeground(new java.awt.Color(255, 255, 255));
        guardar.setText("Guardar");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        jPanel1.add(guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, -1, -1));

        Limpiar.setBackground(new java.awt.Color(29, 41, 57));
        Limpiar.setForeground(new java.awt.Color(255, 255, 255));
        Limpiar.setText("Limpiar");
        Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(Limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, -1, -1));

        jButton1.setText("jButton1");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 190, 670, 320));

        Superior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/SuperiorInterfaz.png"))); // NOI18N
        getContentPane().add(Superior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1540, 80));

        Izquierda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recuadro azul.png"))); // NOI18N
        getContentPane().add(Izquierda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 870));

        ListaPersonal.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        ListaPersonal.setText("Lista de Prestamos");
        getContentPane().add(ListaPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 340, -1));

        TablaPrestamos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Laboratorio", "Solicitante", "Bloque", "Fecha", "Motivo", "Horario"
            }
        ));
        TablaPrestamos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaPrestamosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaPrestamos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
    // Obtener los valores de los campos
    String solicitante = Nombre.getText(); // Nombre del solicitante
    String motivo = Motivo.getText(); // Motivo del préstamo
    Date Fecha = fecha.getDate(); // Fecha del préstamo obtenida desde JCalendar (JDateChooser)
    String Bloque = (String) BloqueComboBox.getSelectedItem(); // Bloque obtenido desde JComboBox
    String Laboratorio = (String) LaboratorioComboBox.getSelectedItem(); // Laboratorio desde JComboBox
    int horario = (Integer) HorarioSpinner.getValue(); // Hora seleccionada desde JSpinner

    // Validación de los campos
    if (solicitante.isEmpty() || motivo.isEmpty() || Fecha == null || Bloque == null || Laboratorio == null || horario == 0){
        JOptionPane.showMessageDialog(null, "Por favor, rellene todos los campos.");
        return;
    }

    // Usuario y contraseña
    String username = JOptionPane.showInputDialog("Ingrese el nombre de usuario");
    String contrasena = JOptionPane.showInputDialog("Ingrese la contraseña");
    String rol = "Personal Academico"; // El rol se mantiene como "Personal Academico"
    int idUsuario = 0;
    int activo = 1;

    try {
        // Conexión a la base de datos
        Connection con = Conexion.obtenerConexion();

        // Insertar datos del usuario
        PreparedStatement psUsuario;
        psUsuario = con.prepareStatement("INSERT INTO usuarios(username, contrasena, rol, activo)VALUES(?, ?, ?, ?)",Statement.RETURN_GENERATED_KEYS);
        psUsuario.setString(1, username);
        psUsuario.setString(2, contrasena);
        psUsuario.setString(3, rol);
        psUsuario.setInt(4, activo);
        psUsuario.executeUpdate();

        // Obtener el ID del usuario recién creado
        ResultSet rs = psUsuario.getGeneratedKeys();
        if (rs.next()) {
            idUsuario = rs.getInt(1);
        } else {
            JOptionPane.showMessageDialog(null, "Error al obtener el ID del usuario");
            return;
        }
        // Insertar datos del préstamo (solicitante, motivo, fecha, bloque, laboratorio, horario)
        PreparedStatement psPrestamo = con.prepareStatement("INSERT INTO prestamos(solicitante, motivo, fecha, bloque, laboratorio, horario) VALUES(?,?,?,?,?,?)");
        psPrestamo.setString(1, solicitante); // Nombre del solicitante
        psPrestamo.setString(2, motivo); // Motivo del préstamo
        psPrestamo.setDate(3, new java.sql.Date(Fecha.getTime())); // Convertir Date a java.sql.Date
        psPrestamo.setString(4, Bloque); // Bloque seleccionado en el JComboBox
        psPrestamo.setString(5, Laboratorio); // Laboratorio seleccionado en el JComboBox
        psPrestamo.setInt(6, horario); // Hora seleccionada en el JSpinner
        psPrestamo.executeUpdate();

        // Mostrar mensaje de éxito
        JOptionPane.showMessageDialog(null, "Registro guardado exitosamente.");
        
        // Redirigir a la interfaz correspondiente (si es necesario)
        FormularioPrestamo interfaz = new FormularioPrestamo();
        interfaz.setVisible(true);

        // Limpiar campos y recargar tabla (si es necesario)
        Limpiar();
        cargarTabla();

    }catch (SQLException ex) {
        System.out.println(ex.toString());
        JOptionPane.showMessageDialog(null, "Error al guardar el registro.");
    }
    }//GEN-LAST:event_guardarActionPerformed

    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed
        Limpiar();
    }//GEN-LAST:event_LimpiarActionPerformed
private void Limpiar(){
    Nombre.setText("");  
    Motivo.setText("");  
    fecha.setDate(null);  // Limpiar el JDateChooser
    BloqueComboBox.setSelectedIndex(-1);  // Reiniciar el JComboBox de bloque
    LaboratorioComboBox.setSelectedIndex(-1);  // Reiniciar el JComboBox de laboratorio
    HorarioSpinner.setValue(1);  // Reiniciar el JSpinner (hora)
}
    private void BloqueComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BloqueComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BloqueComboBoxActionPerformed

    private void TablaPrestamosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaPrestamosMouseClicked
      try {
           int fila =TablaPrestamos.getSelectedRow();
           int id = Integer.parseInt(TablaPrestamos.getValueAt(fila, 0).toString());
           PreparedStatement ps;
           ResultSet rs;
           Connection con=Conexion.obtenerConexion();
           ps= con.prepareStatement("SELECT RU, nombre, apellido, CI, telefono FROM prestamos WHERE id_prestamos=?");/*REVISAR EN GRUPO PUES LA BASE DE DATOS NO TIENE LOS DATOS QUE PIDE ESTA INTERFAZ*/
           ps.setInt(1,id);
           rs=ps.executeQuery();
           
           while (rs.next()) {
               Nombre.setText(rs.getString("Solicitante"));
               Motivo.setText(rs.getString("Motivo"));
               fecha.setDate(rs.getDate("Fecha"));
               BloqueComboBox.setSelectedItem(rs.getString("Bloque"));
               LaboratorioComboBox.setSelectedItem(rs.getString("Laboratorio"));
               HorarioSpinner.setValue(rs.getInt("Horario"));
           }
       }   catch (SQLException ex) {
           JOptionPane.showMessageDialog(null, ex.toString());
       }
       
    }//GEN-LAST:event_TablaPrestamosMouseClicked
    private void cargarTabla(){
        DefaultTableModel modeloTabla=(DefaultTableModel) TablaPrestamos.getModel();
        modeloTabla.setRowCount(0);
        PreparedStatement ps;
        ResultSet rs;
        java.sql.ResultSetMetaData rsmd;
        int columnas;
        
        int [] anchos= {10, 50, 100 ,100, 80, 90, 50};
        for (int i=0; i<TablaPrestamos.getColumnCount(); i++){
            TablaPrestamos.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
        }
        try {
            Connection con=Conexion.obtenerConexion();
            ps = con.prepareStatement(
                    "SELECT t.id_personal, t.RU, t.nombre, t.apellido, t.CI, t.telefono, u.activo "
                    +"FROM prestamos p"                                                             /*hacer en grupo para analizar la base de datos */
                    +"INNER JOIN usuarios u ON t.id_usuario = u.id_usuario"
            );
            rs= ps.executeQuery();
            rsmd=rs.getMetaData();
            columnas=rsmd.getColumnCount();
            
            while (rs.next()){
                Object[] fila=new Object[columnas];
                for (int indice=0; indice<columnas-1; indice++){
                    fila[indice]= rs.getObject(indice+1);
                }
                //activo o inactivo
                fila[columnas-1]=rs.getInt("Activo")==1?"Activo":"Inactivo";
                modeloTabla.addRow(fila);
            }
        } catch (SQLException ex){
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }
  /**
     * @param args the command line arguments
     */
public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception e){
            e.printStackTrace();
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioPrestamo().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BloqueComboBox;
    private javax.swing.JSpinner HorarioSpinner;
    private javax.swing.JLabel Izquierda;
    private javax.swing.JComboBox<String> LaboratorioComboBox;
    private javax.swing.JButton Limpiar;
    private javax.swing.JLabel ListaPersonal;
    private javax.swing.JLabel LogoSale;
    private javax.swing.JTextField Motivo;
    private javax.swing.JTextField Nombre;
    private javax.swing.JLabel Superior;
    private javax.swing.JTable TablaPrestamos;
    private com.toedter.calendar.JDateChooser fecha;
    private javax.swing.JButton guardar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}