package TecnicoDePrestamos;


import ConexionLogin.Conexion;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import java.sql.Connection;
import java.sql.*;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Rafael
 */
public class ListaPrestamos extends javax.swing.JFrame {

    private int idusuario;

    /**
     * Creates new form GestionEquipos
     */
    public ListaPrestamos() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LogoSale = new javax.swing.JLabel();
        perfil1 = new javax.swing.JLabel();
        Superior = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnCerrarSesion1 = new javax.swing.JButton();
        btnCerrarSesion2 = new javax.swing.JButton();
        btnCerrarSesion3 = new javax.swing.JButton();
        btnCerrarSesion4 = new javax.swing.JButton();
        btnCerrarSesion5 = new javax.swing.JButton();
        btnCerrarSesion6 = new javax.swing.JButton();
        btnCerrarSesion7 = new javax.swing.JButton();
        btnCerrarSesion8 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();
        Izquierda = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaSolicitudes = new javax.swing.JTable();
        ListadePrestamos = new javax.swing.JLabel();
        BuscarSolicitudes = new javax.swing.JButton();
        ActualizarTabla = new javax.swing.JButton();
        FondoBlanco = new javax.swing.JLabel();
        FondoGris1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LogoSale.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logosaleint.png"))); // NOI18N
        getContentPane().add(LogoSale, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 170, 60));

        perfil1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconouser.png"))); // NOI18N
        getContentPane().add(perfil1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1480, 10, 40, -1));

        Superior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/SuperiorInterfaz.png"))); // NOI18N
        getContentPane().add(Superior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1540, 60));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Menú Principal");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoBar.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 230, 40));

        btnCerrarSesion1.setBackground(new java.awt.Color(29, 41, 57));
        btnCerrarSesion1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCerrarSesion1.setForeground(new java.awt.Color(241, 241, 241));
        btnCerrarSesion1.setText("Cerrar Sesión");
        btnCerrarSesion1.setBorder(null);
        btnCerrarSesion1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCerrarSesion1MouseExited(evt);
            }
        });
        btnCerrarSesion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesion1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrarSesion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 229, 40));

        btnCerrarSesion2.setBackground(new java.awt.Color(29, 41, 57));
        btnCerrarSesion2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCerrarSesion2.setForeground(new java.awt.Color(241, 241, 241));
        btnCerrarSesion2.setText("Cerrar Sesión");
        btnCerrarSesion2.setBorder(null);
        btnCerrarSesion2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCerrarSesion2MouseExited(evt);
            }
        });
        btnCerrarSesion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesion2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrarSesion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 229, 40));

        btnCerrarSesion3.setBackground(new java.awt.Color(29, 41, 57));
        btnCerrarSesion3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCerrarSesion3.setForeground(new java.awt.Color(241, 241, 241));
        btnCerrarSesion3.setText("Cerrar Sesión");
        btnCerrarSesion3.setBorder(null);
        btnCerrarSesion3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCerrarSesion3MouseExited(evt);
            }
        });
        btnCerrarSesion3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesion3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrarSesion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 229, 40));

        btnCerrarSesion4.setBackground(new java.awt.Color(29, 41, 57));
        btnCerrarSesion4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCerrarSesion4.setForeground(new java.awt.Color(241, 241, 241));
        btnCerrarSesion4.setText("Cerrar Sesión");
        btnCerrarSesion4.setBorder(null);
        btnCerrarSesion4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCerrarSesion4MouseExited(evt);
            }
        });
        btnCerrarSesion4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesion4ActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrarSesion4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 229, 40));

        btnCerrarSesion5.setBackground(new java.awt.Color(29, 41, 57));
        btnCerrarSesion5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCerrarSesion5.setForeground(new java.awt.Color(241, 241, 241));
        btnCerrarSesion5.setText("Cerrar Sesión");
        btnCerrarSesion5.setBorder(null);
        btnCerrarSesion5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCerrarSesion5MouseExited(evt);
            }
        });
        btnCerrarSesion5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesion5ActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrarSesion5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 229, 40));

        btnCerrarSesion6.setBackground(new java.awt.Color(29, 41, 57));
        btnCerrarSesion6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCerrarSesion6.setForeground(new java.awt.Color(241, 241, 241));
        btnCerrarSesion6.setText("Cerrar Sesión");
        btnCerrarSesion6.setBorder(null);
        btnCerrarSesion6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCerrarSesion6MouseExited(evt);
            }
        });
        btnCerrarSesion6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesion6ActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrarSesion6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 229, 40));

        btnCerrarSesion7.setBackground(new java.awt.Color(29, 41, 57));
        btnCerrarSesion7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCerrarSesion7.setForeground(new java.awt.Color(241, 241, 241));
        btnCerrarSesion7.setText("Cerrar Sesión");
        btnCerrarSesion7.setBorder(null);
        btnCerrarSesion7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCerrarSesion7MouseExited(evt);
            }
        });
        btnCerrarSesion7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesion7ActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrarSesion7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 229, 40));

        btnCerrarSesion8.setBackground(new java.awt.Color(29, 41, 57));
        btnCerrarSesion8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCerrarSesion8.setForeground(new java.awt.Color(241, 241, 241));
        btnCerrarSesion8.setText("Cerrar Sesión");
        btnCerrarSesion8.setBorder(null);
        btnCerrarSesion8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCerrarSesion8MouseExited(evt);
            }
        });
        btnCerrarSesion8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesion8ActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrarSesion8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 229, 40));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrarsesion.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 820, 20, 30));

        btnCerrarSesion.setBackground(new java.awt.Color(29, 41, 57));
        btnCerrarSesion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCerrarSesion.setForeground(new java.awt.Color(241, 241, 241));
        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.setBorder(null);
        btnCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCerrarSesionMouseExited(evt);
            }
        });
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 813, 229, 40));

        Izquierda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recuadro azul.png"))); // NOI18N
        getContentPane().add(Izquierda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 870));

        TablaSolicitudes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Laboratorio", "Docente", "Motivo", "Bloque", "Sección", "Fecha", "Horario Inicio", "Horario Fin", "Estado", "Motivo del rechazo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, true, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TablaSolicitudes);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 1220, 640));

        ListadePrestamos.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        ListadePrestamos.setText("Historial de Solicitudes");
        getContentPane().add(ListadePrestamos, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, -1, -1));

        BuscarSolicitudes.setText("Buscar Solicitudes");
        BuscarSolicitudes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarSolicitudesActionPerformed(evt);
            }
        });
        getContentPane().add(BuscarSolicitudes, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, -1, -1));

        ActualizarTabla.setText("Actualizar Tabla");
        ActualizarTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarTablaActionPerformed(evt);
            }
        });
        getContentPane().add(ActualizarTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, -1, -1));

        FondoBlanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo_2.png"))); // NOI18N
        getContentPane().add(FondoBlanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 1250, 760));

        FondoGris1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo_3.png"))); // NOI18N
        getContentPane().add(FondoGris1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1680, 920));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void cargarTabla() {
        DefaultTableModel modeloTabla = (DefaultTableModel) TablaSolicitudes.getModel();
        modeloTabla.setRowCount(0);  

        PreparedStatement ps;
        ResultSet rs;
        ResultSetMetaData rsmd;
        int columnas;

        try {
            
            Connection con = Conexion.obtenerConexion();  
            ps = con.prepareStatement(
                    "SELECT p.id_prestamo, l.Nombre_lab, CONCAT(pa.nombre, ' ', pa.apellido) AS nombre_completo, "
                    + "p.motivo, l.bloque, l.seccion, p.fecha, p.horario_inicio, p.horario_fin, p.estado, p.motivo_rechazo "
                    + "FROM prestamos p "
                    + "INNER JOIN laboratorios l ON p.ID_lab = l.ID_lab "
                    + "INNER JOIN personal_academico pa ON p.id_personal_academico = pa.id_personal_academico "            
            );
            rs = ps.executeQuery();
            rsmd = rs.getMetaData();
            columnas = rsmd.getColumnCount();

            while (rs.next()) {
                Object[] fila = new Object[columnas];
                for (int indice = 0; indice < columnas; indice++) {
                    fila[indice] = rs.getObject(indice + 1);
                }
                modeloTabla.addRow(fila);  
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.toString(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    private boolean haySolicitudesPendientes() {
        boolean pendiente = false;
        try {
            Connection con = Conexion.obtenerConexion();
            PreparedStatement ps = con.prepareStatement(
                    "SELECT COUNT(*) FROM prestamos WHERE estado = 'Pendiente'"
            );
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                pendiente = rs.getInt(1) > 0; 
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al obtener solicitudes pendientes: " + ex.getMessage());
        }
        return pendiente;
    }
    private void actualizarColorBotonSolicitud() {
        if (haySolicitudesPendientes()) {
          
            BuscarSolicitudes.setBackground(Color.RED);
            BuscarSolicitudes.setText("¡Solicitudes Pendientes!");
        } else {
            
            BuscarSolicitudes.setBackground(UIManager.getColor("Button.background"));
            BuscarSolicitudes.setText("Buscar Solicitudes");
        }
    }
    private void BuscarSolicitudesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarSolicitudesActionPerformed
     SolicitudPendiente solicitudpendientes = new SolicitudPendiente();
     solicitudpendientes.setVisible(true);
     
    }//GEN-LAST:event_BuscarSolicitudesActionPerformed

    private void ActualizarTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarTablaActionPerformed
        cargarTabla();
        actualizarColorBotonSolicitud();
    }//GEN-LAST:event_ActualizarTablaActionPerformed

    private void btnCerrarSesion1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSesion1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarSesion1MouseExited

    private void btnCerrarSesion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarSesion1ActionPerformed

    private void btnCerrarSesion2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSesion2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarSesion2MouseExited

    private void btnCerrarSesion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesion2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarSesion2ActionPerformed

    private void btnCerrarSesion3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSesion3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarSesion3MouseExited

    private void btnCerrarSesion3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesion3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarSesion3ActionPerformed

    private void btnCerrarSesion4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSesion4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarSesion4MouseExited

    private void btnCerrarSesion4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesion4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarSesion4ActionPerformed

    private void btnCerrarSesion5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSesion5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarSesion5MouseExited

    private void btnCerrarSesion5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesion5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarSesion5ActionPerformed

    private void btnCerrarSesion6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSesion6MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarSesion6MouseExited

    private void btnCerrarSesion6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesion6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarSesion6ActionPerformed

    private void btnCerrarSesion7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSesion7MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarSesion7MouseExited

    private void btnCerrarSesion7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesion7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarSesion7ActionPerformed

    private void btnCerrarSesion8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSesion8MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarSesion8MouseExited

    private void btnCerrarSesion8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesion8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarSesion8ActionPerformed

    private void btnCerrarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSesionMouseExited

    }//GEN-LAST:event_btnCerrarSesionMouseExited

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception e){
            e.printStackTrace();
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ListaPrestamos frame = new ListaPrestamos();
                frame.setVisible(true);
                frame.actualizarColorBotonSolicitud(); 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActualizarTabla;
    private javax.swing.JButton BuscarSolicitudes;
    private javax.swing.JLabel FondoBlanco;
    private javax.swing.JLabel FondoGris1;
    private javax.swing.JLabel Izquierda;
    private javax.swing.JLabel ListadePrestamos;
    private javax.swing.JLabel LogoSale;
    private javax.swing.JLabel Superior;
    private javax.swing.JTable TablaSolicitudes;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnCerrarSesion1;
    private javax.swing.JButton btnCerrarSesion2;
    private javax.swing.JButton btnCerrarSesion3;
    private javax.swing.JButton btnCerrarSesion4;
    private javax.swing.JButton btnCerrarSesion5;
    private javax.swing.JButton btnCerrarSesion6;
    private javax.swing.JButton btnCerrarSesion7;
    private javax.swing.JButton btnCerrarSesion8;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel perfil1;
    // End of variables declaration//GEN-END:variables
}
